apiVersion: v1
kind: Service
metadata:
  name: endomorphineedge-service
spec:
  selector:
    app: endomorphineedge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
